### PR TITLE
fix(page-controller): improve contenteditable input with proper events

### LINKED ISSUE #168: [Bug] Can't type into LinkedIn post editor (contenteditable div)
### What happened?

It is failed to type into LinkedIn’s post editor here because it’s a contenteditable div (not an input/textarea)

Image

### Code

```typescript

```

### Browser

Chrome Extension

### version

_No response_

### Community Communication / 社区沟通

- [x] I will be polite and respectful. / 我会保持礼貌与尊重。
- [x] I will share constructive, actionable suggestions. / 我会提供建设性、可行动的建议。
- [x] I have read the Code of Conduct. / 我已阅读行为准则。

### PR DESCRIPTION
**Pull request by JasonOA888**
## Problem

Input into contenteditable elements (like LinkedIn post editor) fails because simply setting `innerText` does not trigger framework event listeners.

Fixes #168

## Solution

Dispatch a full sequence of events that rich text editors expect:

1. **beforeinput** - Required by React apps (Draft.js, Slate.js)
2. **input** - Standard DOM event
3. **keydown/keyup** - For frameworks listening to keyboard events
4. **change** - For form validation
5. **blur + refocus** - To trigger change detection

## Technical Details

Many modern rich text editors (LinkedIn, Facebook, Twitter, etc.) use contenteditable divs with framework-specific event listeners. Simply setting `innerText` bypasses these listeners, causing the input to not register.

This fix follows the same event dispatch pattern used by Puppeteer's `type` method and browser automation best practices.

## Testing

Should work on:
- LinkedIn post editor
- Draft.js editors
- Slate.js editors
- Quill editors
- Any contenteditable with React/Vue listeners

### CODE REVIEW

**Comment by mrxiaojie** [comment]
中午好！您的邮件我已经收到了，谢谢您的支持！

**Comment by gaomeng1900** [comment]
The Copilot reviews seems to be unnecessarily complicated. I'd rather we keep things simple for now.

**Comment by gaomeng1900** [comment]
It doesn't seem to work on slate and draft. I'm looking into this.

File: packages/page-controller/src/actions.ts [hunk 1]
```diff
@@ -114,14 +114,101 @@ export async function inputTextElement(element: HTMLElement, text: string) {
 	await clickElement(element)
 
 	if (isContentEditable) {
-		element.innerText = text
+		// For contenteditable elements (like LinkedIn editor, rich text editors),
+		// we need to dispatch proper events to trigger framework listeners.
+		// Many frameworks (React, Vue, etc.) listen to specific events.
+		const editableElement = element as HTMLElement & { innerText: string }
```
Comment (gaomeng1900) [inline packages/page-controller/src/actions.ts]: redundant

File: packages/page-controller/src/actions.ts [hunk 2]
```diff
@@ -114,14 +114,101 @@ export async function inputTextElement(element: HTMLElement, text: string) {
...
+
+		try {
+			// Focus the element first
+			editableElement.focus()
```
Comment (gaomeng1900) [inline packages/page-controller/src/actions.ts]: `clickElement` has been called at L114.

File: packages/page-controller/src/actions.ts [hunk 3]
```diff
@@ -114,14 +114,101 @@ export async function inputTextElement(element: HTMLElement, text: string) {
...
+
+			// Dispatch keydown first (typical event order: keydown -> beforeinput -> mutation -> input -> keyup)
+			// Only for single-character input to maintain semantic consistency
+			if (text.length === 1) {
```
Comment (gaomeng1900) [inline packages/page-controller/src/actions.ts]: Semantically correct, but limiting this to text.length === 1 creates inconsistent behaviour.

File: packages/page-controller/src/actions.ts [hunk 4]
```diff
@@ -114,14 +114,101 @@ export async function inputTextElement(element: HTMLElement, text: string) {
...
+			}
+
+			// Dispatch change event (for good measure)
+			editableElement.dispatchEvent(new Event('change', { bubbles: true }))
+
+			// Trigger blur for validation, then refocus
+			// blur() dispatches its own focusout event, so we don't need a duplicate
+			editableElement.blur()
+			editableElement.focus()
+		} finally {
```
Comment (gaomeng1900) [inline packages/page-controller/src/actions.ts]: Prefer throwing an error here over silently dropping it.

File: packages/page-controller/src/actions.ts [hunk 5]
```diff
@@ -114,14 +114,101 @@ export async function inputTextElement(element: HTMLElement, text: string) {
...
+			// Dispatch beforeinput event for insertion (important for React apps)
+			// Check if canceled - if so, skip the mutation but continue cleanup
+			const beforeInputEvent = new InputEvent('beforeinput', {
+				bubbles: true,
+				cancelable: true,
+				inputType: 'insertText',
+				data: text,
+			})
+			const notCanceled = editableElement.dispatchEvent(beforeInputEvent)
+			const shouldInsert = notCanceled && !beforeInputEvent.defaultPrevented
```
Comment (gaomeng1900) [inline packages/page-controller/src/actions.ts]: According to https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent#return_value ,
the `!beforeInputEvent.defaultPrevented` is redundant.

**Comment by gaomeng1900** [comment]
I tested this `synthetic event` approach in the Chrome extension with the following tasks:

```
1. Open https://quilljs.com/ and input "HAHA" in the example editor
2. Go to https://www.slatejs.org/examples/richtext and replace the text with "HAHA"
3. Open https://draftjs.org/ and input "HAHA" in the "Try it out" editor
4. Go to https://www.linkedin.com/feed/ and post a new feed with "HAHA"
5. Goto https://kkpnnkkzov.csb.app/, replace "task 1" with "task AAA"
```

Does not work for slatejs and draftjs.


After trying many approaches, I came to the following conclusions:

- **draftjs** cannot be supported safely via DOM manipulation — this appears to be by design. It's not maintained anyway.
- **Monaco and CodeMirror** can only be controlled by obtaining their JS instances directly; there is no reliable path through `contenteditable` elements alone.

Also. **`execCommand`** works better (works for LinkedIn, Quill, and Draft.js). But the API is deprecated. I'll leave it in the comments for now and revisit later.

**Comment by gaomeng1900** [comment]
I used force-push to get ride of the empty commit (9ab29de  docs: note Slate/Draft.js limitations). Did i break something? @JasonOA888
