### PR TITLE
fix: add execCommand fallback for contenteditable input

### LINKED ISSUE #168: [Bug] Can't type into LinkedIn post editor (contenteditable div)
### What happened?

It is failed to type into LinkedIn’s post editor here because it’s a contenteditable div (not an input/textarea)

Image

### Code

```typescript

```

### Browser

Chrome Extension

### version

_No response_

### Community Communication / 社区沟通

- [x] I will be polite and respectful. / 我会保持礼貌与尊重。
- [x] I will share constructive, actionable suggestions. / 我会提供建设性、可行动的建议。
- [x] I have read the Code of Conduct. / 我已阅读行为准则。

### PR DESCRIPTION
**Pull request by voidborne-d**
## Problem

When Page Agent tries to type into contenteditable elements (e.g. LinkedIn post editor, #168), the synthetic event approach (Plan A) fires `beforeinput`/`input` events and sets `innerText`, but some editors' internal state doesn't update — the text appears momentarily then gets wiped, or never appears at all.

This happens because editors like LinkedIn's use framework-level event handlers that don't respond to synthetic `InputEvent` dispatches.

## Solution

After executing Plan A, we now **verify** the text was actually inserted by checking `element.innerText`. If it wasn't, we automatically fall back to **Plan B: `execCommand`**.

The fallback:
1. Focuses the element
2. Uses `Selection`/`Range` API to select all content
3. Deletes existing content via `execCommand('delete')`
4. Inserts new text via `execCommand('insertText')`

### Why this works

`execCommand` is deprecated but still widely supported by all major browsers. More importantly, it integrates **natively** with the browser's editing machinery — rich-text editors built on contenteditable (LinkedIn, Quill, Slate.js, ProseMirror) all respond to it correctly because it flows through the same code path as real user input.

### What stays the same

- Plan A (synthetic events) is still tried first — it works well for React contenteditable and simpler editors
- The change/blur event dispatch is unchanged
- No behavior change for `<input>` or `<textarea>` elements

Fixes #168

### CODE REVIEW

File: packages/page-controller/src/actions.ts [hunk 1]
```diff
@@ -119,11 +119,16 @@ export async function inputTextElement(element: HTMLElement, text: string) {
...
+		// to Plan B (execCommand) if the text wasn't actually inserted.
+		//
 		// Plan A: Dispatch synthetic events
-		// Works: LinkedIn, React contenteditable, Quill.
-		// Fails: Slate.js
+		// Works: React contenteditable, Quill, some LinkedIn versions.
+		// Fails: Slate.js, some contenteditable editors that ignore synthetic events.
 		// Sequence: beforeinput -> mutation -> input -> change -> blur
 
+		let planASucceeded = false
```
Comment (gaomeng1900) [inline packages/page-controller/src/actions.ts]: Only used once. Better using const
